#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allclean

runApplication surfaceFeatureExtract
runApplication blockMesh
runApplication decomposePar -copyZero
runParallel snappyHexMesh -overwrite
# runParallel checkMesh -constant
runApplication reconstructParMesh -constant


#------------------------------------------------------------------------------
